/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#366936",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#ffb780",
        "tertiary-container": "#824508",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#1e5121",
        "on-background": "#191c1d",
        "tertiary-fixed": "#ffdcc4",
        "on-tertiary-fixed": "#2f1400",
        "surface-container-high": "#e7e8e9",
        "surface-dim": "#d9dadb",
        "on-tertiary-fixed-variant": "#6f3800",
        "on-primary-fixed": "#002204",
        "outline": "#72796e",
        "outline-variant": "#c1c9bc",
        "inverse-on-surface": "#f0f1f2",
        "primary": "#134718",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#2b1700",
        "secondary-fixed": "#ffddb8",
        "surface-bright": "#f8f9fa",
        "inverse-primary": "#9cd596",
        "on-error-container": "#93000a",
        "inverse-surface": "#2e3132",
        "surface": "#f8f9fa",
        "secondary": "#765937",
        "secondary-fixed-dim": "#e6c096",
        "on-secondary-fixed-variant": "#5c4222",
        "surface-container-low": "#f3f4f5",
        "on-error": "#ffffff",
        "primary-fixed": "#b7f1b0",
        "on-secondary": "#ffffff",
        "secondary-container": "#fed6ab",
        "primary-fixed-dim": "#9cd596",
        "surface-container": "#edeeef",
        "on-tertiary-container": "#ffbb88",
        "on-primary-container": "#9fd798",
        "primary-container": "#2c5f2d",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191c1d",
        "tertiary": "#613000",
        "on-secondary-container": "#785b39",
        "background": "#f8f9fa",
        "surface-variant": "#e1e3e4",
        "surface-container-highest": "#e1e3e4",
        "on-surface-variant": "#41493f",
        "error-container": "#ffdad6"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter", "PingFang SC", "Microsoft YaHei", "sans-serif"],
        "label": ["Inter", "PingFang SC", "Microsoft YaHei", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}